server:
  port: 8083

spring:
  application:
    name: coordinator-service

seata:
  enabled: true
  enable-auto-data-source-proxy: false
  application-id: coordinator-service
  tx-service-group: order_tx_group
  service:
    vgroup-mapping:
      order_tx_group: default
    grouplist:
      default: 127.0.0.1:8091

grpc:
  client:
    order-service:
      address: 'static://${APP_SERVICES_ORDER_GRPC_HOST:localhost}:9091'
      negotiation-type: plaintext
    payment-service:
      address: 'static://${APP_SERVICES_PAYMENT_GRPC_HOST:localhost}:9092'
      negotiation-type: plaintext
